version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: php-fpm
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - .:/var/www
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    networks:
      - laravel_nginx

  mysql:
    image: mysql:8.0
    container_name: laravel_db
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - laravel_nginx

  nginx:
      image: nginx:alpine
      container_name: laravel_nginx
      volumes:
        - .:/var/www
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "9000:80"
      networks:
        - laravel_nginx
      depends_on:
        - app

networks:
  laravel_nginx:
    driver: bridge

volumes:
  db_data:
